pipeline {
    agent any
    environment {
        REGISTRY = "parkjsdev3232"
        IMAGE_TAG = "latest"
    }
    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/park-jsdev/phone-validator.git'
            }
        }
        stages {
        stage('Build') {
            steps {
                script {
                    docker.build("${REGISTRY}/frontend:${IMAGE_TAG}", "./mern-app/frontend")
                    docker.build("${REGISTRY}/backend:${IMAGE_TAG}", "./mern-app/backend")
                }
            }
        }
        stage('Push') {
            steps {
                script {
                    docker.withRegistry('', 'docker-hub-credentials') {
                        docker.image("${REGISTRY}/frontend:${IMAGE_TAG}").push()
                        docker.image("${REGISTRY}/backend:${IMAGE_TAG}").push()
                    }
                }
            }
        }
        stage('Deploy') {
            steps {
                kubernetesDeploy(
                    configs: 'k8s-deployment.yaml',
                    kubeconfigId: 'k8s-token',
                    secretName: 'jenkins-token'
                )
            }
        }
    }
}
